### ISSUE TITLE
Admin dashboard on mobile - Monthly adoptions graph not responsive

### ISSUE THREAD

**Issue by CarelleR** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#108]
<img width="470" alt="Screen Shot 2023-10-27 at 10 43 07 pm" src="https://github.com/CarelleR/ProgrammingProjectOUA_2023_SP3_Team2/assets/71162432/d3661c90-ffe7-44f0-93bf-e105e4d4f2ae">

Perhaps you can scale the div with the graph or make the div scrollable (ref overflow / scroll on bootstrap)

**Comment by AngusDobson** [comment]
#160 has made the graph responsive
