### ISSUE TITLE
Non-responsive graphics on homepage 

### ISSUE THREAD

**Issue by CarelleR** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#120]
![387572350_301597132647089_7300524701123047078_n](https://github.com/CarelleR/ProgrammingProjectOUA_2023_SP3_Team2/assets/71162432/28e88d85-2a3f-426b-aab5-6ec25901d551)

Animated down arrow overlaps graphics on mobile

**Comment by AngusDobson** [comment]
This is reliant on the height of the screen, uncertain if this is something we can resolve, unless we remove the icon on mobile devices? Thoughts?

**Comment by CarelleR** [comment]
If you're working with viewports, ideally, you would make a hero section the height of the viewport. If on mobile, the hero section is just the the text, then that section would be the height of the viewport and the dog would collapse under the viewport. Yes, an easy solution would just be to remove the arrow when the dog collapses. I think it would look nicer than it bouncing over his face 🐶
