### ISSUE TITLE
Invalid HTML - Home, about & contact pages

### ISSUE THREAD

**Issue by CarelleR** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#169]
Can you please take a look?

<img width="955" alt="Screen Shot 2023-11-11 at 9 00 37 pm" src="https://github.com/CarelleR/ProgrammingProjectOUA_2023_SP3_Team2/assets/71162432/a05d086c-e894-446c-aa71-2f2cbd62afb5">

<img width="1615" alt="Screen Shot 2023-11-11 at 8 59 56 pm" src="https://github.com/CarelleR/ProgrammingProjectOUA_2023_SP3_Team2/assets/71162432/c906c32d-7fc6-4125-9564-a3d289ec9563">

<img width="1628" alt="Screen Shot 2023-11-11 at 8 59 40 pm" src="https://github.com/CarelleR/ProgrammingProjectOUA_2023_SP3_Team2/assets/71162432/e7597d39-a19d-4e8b-9eb3-9ce40d047d83">

**Comment by ary-na** [comment]
@CarelleR These were suggestions based on Google PageSpeed Insights standards and are valid in the lighthouse calculator. Changing them will affect the lighthouse calculator's score. Your call, let me know if you want me to change/fix them.
