### ISSUE TITLE
Profile Back Button Function

### ISSUE THREAD

**Issue by s3526562a** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#58]
Test Case TC2.01 - Test Run 01
The Back button in the Adopters profile re-enables edit mode.

Is this correct function for this button?

**Comment by CarelleR** [comment]
Can you close this if it's ok now @s3526562a ?

**Comment by s3526562a** [comment]
Yes, this has been checked indirectly in many of the test case tuns performed today.

Issue resolved. Close.
